services:
  web-prod:
    container_name: web-prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:8092:80"
