export enum Permission {
  /* AccountScreen */
  VIEW_SETTINGS_SECTION = 'VIEW_SETTINGS_SECTION',
  VIEW_SALES_ANALYTICS = 'VIEW_SALES_ANALYTICS',

  /* DailySalesScreen  */
  VIEW_DAILY_METRICS = 'VIEW_DAILY_METRICS',
  VIEW_PAYMENT_DISTRIBUTION = 'VIEW_PAYMENT_DISTRIBUTION',
  VIEW_TOTALS_ROW = 'VIEW_TOTALS_ROW',
  VIEW_DAILYSALES_SCREEN_METRICS = 'VIEW_DAILYSALES_SCREEN_METRICS',
  VIEW_DAILYSALES_SCREEN_SUBTAB = 'VIEW_DAILYSALES_SCREEN_SUBTAB',
  VIEW_DAILYSALES_SCREEN_DATE_HEADER = 'VIEW_DAILYSALES_SCREEN_DATE_HEADER',

  /* OrdersScreen */
  VIEW_CREDIT_ORDERS = 'VIEW_CREDIT_ORDERS',
  VIEW_ORDER_SCREEN_METRICS = 'VIEW_ORDER_SCREEN_METRICS',
  VIEW_ORDERS_SCREEN_SUBTAB = 'VIEW_ORDERS_SCREEN_SUBTAB',

  /* HomeScreen */
  VIEW_HOME_SCREEN_METRICS = 'VIEW_HOME_SCREEN_METRICS',
  VIEW_HOME_SCREEN_DAILYSALES_TOTALSALES_AMOUNT = 'VIEW_HOME_SCREEN_DAILYSALES_TOTALSALES_AMOUNT',
  VIEW_HOME_SCREEN_DAILYSALES_CASH_AND_QR_AMOUNT = 'VIEW_HOME_SCREEN_DAILYSALES_CASH_AND_QR_AMOUNT',
  VIEW_HOME_SCREEN_PAYMENTDISTRIBUTION_AMOUNT = 'VIEW_HOME_SCREEN_PAYMENTDISTRIBUTION_AMOUNT',
}
